language: php
php:
  - 5.5
  - 5.4
  - hhvm
  - nightly
before_script: 
 - composer self-update
  - composer install -n --prefer-dist
  - ./vendor/bin/codecept build

# Run tests through Codeception
script:   
- ./vendor/bin/codecept run


