language: php
php:
  - 5.5
  - 5.4
  - hhvm
  - nightly
matrix:
  allow_failures:
    - php: hhvm
env:
  - DB_HOST="127.0.0.1" DB_NAME="jeff_proseeds" DB_USERNAME="root"
before_script: 
  - mysql -e 'create database jeff_proseeds;'
  - php artisan migrate --force
  - ./vendor/bin/codecept build

# Run tests through Codeception
script:   
- ./vendor/bin/codecept run
deploy:
  provider: heroku
  api_key: "9d8f7081-28e1-48fc-968a-c3f2f1b58d1c" 
  app: 'mypropeller'

