language: php
php:
  - 5.5
  - 5.4
  - hhvm
  - nightly
matrix:
  allow_failures:
    - php: hhvm
env:
  - DB_HOST="127.0.0.1" DB_NAME="jeff_proseeds" DB_USERNAME="root"
before_script: 
  - composer self-update
  - touch storage/testing.sqlite
  - composer install -n --prefer-dist
  - mysql -e 'create database jeff_proseeds;'
  - php artisan migrate --force
  - ./vendor/bin/codecept build

# Run tests through Codeception
script:   
- ./vendor/bin/codecept run

